### ISSUE TITLE
[用户体验] 烟花教程标识不清的反馈

### ISSUE THREAD

**Issue by ghost** [YZBWDLT/Minecraft-Bedrock-World-30-Ways-to-Die-2#13]
# [用户体验] 烟花教程标识不清的反馈

烟花教程玩家会获得三个物品：“下一步”“返回”“退出”。

其中，返回被指向的操作是“上一步”。对此，在自定义关卡之中，“返回”的定义是“退出自定义关卡”。

此种表示会导致玩家认识错误。

附图：在烟花教程之中出现的“返回”。

![截屏2023-07-04 14 49 39](https://github.com/YZBWDLT/Minecraft-Bedrock-World-30-Ways-to-Die-2/assets/72379760/6e08d591-abff-4116-921a-2384bf2e484f)

**Comment by YZBWDLT** [comment]
目前来说的话，这个物品搭配确实算是比较适合的了
因为目前的物品搭配里面，“下一步”对应的“上一步”适合由“返回”胜任，地图里其他涉及到“上一步”的操作都是用的“返回”
至于要不要添加一个上一步的物品，高情商地说，这会大幅增加工作量
