### ISSUE TITLE
在非开发者模式的情况下，使用可能导致游戏模式更改的功能会导致崩溃

### ISSUE THREAD

**Issue by YZBWDLT** [YZBWDLT/Minecraft-Bedrock-World-30-Ways-to-Die-2#2]

**Comment by ghost** [comment]
好的工作，爱来自瓷器。

**Comment by YZBWDLT** [comment]
> 

没有用处的评论，恨来自瓷器。

**Comment by YZBWDLT** [comment]
> 好的工作，爱来自瓷器。

没有用处的评论，恨来自瓷器。

**Comment by YZBWDLT** [comment]
**新问题**
如果在设置中心改完创造模式使用返回会立即崩溃，100%触发
虽然尚不清楚为什么改了创造模式一返回就崩，似乎生存模式和冒险模式并不会触发这个问题。考虑到自定义关卡退出的时候玩家也是处于创造模式下，有理由猜测可能是创造模式导致的地图不稳定。将对创造模式的玩家进行限制以及命令优化。

**Comment by YZBWDLT** [comment]
### 问题原因
使用了实验性玩法的数据驱动物品在run_command的稳定性上实在不敢恭维。在手机版创造模式下使用返回或跳过等可能导致游戏模式更改的功能；当手动执行同样的函数时，不崩溃；当在同样条件下使用物品稳定崩溃。
